const tips = [
    { title: "Morning Wall Push-Ups", content: "Do 20 wall push-ups right after waking up. They boost arm strength and wake you up without equipment. Perfect for small spaces!", keywords: "wall push-ups, morning exercise, no equipment workout", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Two-Minute Stress Buster", content: "Practice deep breathing for 2 minutes: inhale 4 seconds, hold 4, exhale 4. Reduces stress and boosts energy. Do it anywhere!", keywords: "deep breathing exercise, stress relief, quick mindfulness", image: "https://images.unsplash.com/photo-1509909751488-998f78ad4895?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Staircase Calf Raises", content: "Use a staircase for 15 calf raises: up on toes, hold, lower slowly. Strengthens calves and improves balance. No gym needed!", keywords: "calf raises, staircase workout, leg strength", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Desk Chair Dips", content: "Use a sturdy chair for 10 tricep dips during a work break. Keep elbows back and lower slowly. Tones arms fast!", keywords: "chair dips, tricep workout, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Squat Boost", content: "Do 15 bodyweight squats in 1 minute. Engages glutes, quads, and core. Add a pause at the bottom for extra burn!", keywords: "bodyweight squats, quick leg workout, glute exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Hydration Hack for Energy", content: "Drink a glass of water first thing in the morning. It kickstarts metabolism and fights fatigue. Add lemon for flavor!", keywords: "hydration tips, morning energy, metabolism boost", image: "https://images.unsplash.com/photo-1612884237056-ced35c6e3fd2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Side Stretch", content: "Stand and reach one arm overhead, stretching to the side for 20 seconds each side. Relieves tension and improves flexibility. Do it during a break!", keywords: "side stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Jump Squats for Power", content: "Perform 10 jump squats: squat low, then explode upward. Builds leg strength and cardio. Rest 15 seconds between sets!", keywords: "jump squats, leg power, cardio workout", image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Core Twist", content: "Sit and twist your torso side-to-side for 30 seconds. Engages obliques and strengthens core. No equipment needed!", keywords: "core twist, oblique workout, quick abs", image: "https://images.unsplash.com/photo-1518614366606-8a8a9d7e15bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Walk and Talk Fitness", content: "Take phone calls while walking briskly for 10 minutes. Burns calories and boosts mood. Use stairs for extra intensity!", keywords: "walking workout, phone call exercise, daily fitness", image: "https://images.unsplash.com/photo-1557330359-30b6d36a3eb5?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "One-Minute Burpee Blast", content: "Do as many burpees as you can in 60 seconds. Full-body workout that spikes heart rate. Rest and repeat twice!", keywords: "burpee workout, full body exercise, quick cardio", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Leg Extensions", content: "While seated, extend one leg straight out, hold for 5 seconds, switch for 10 reps. Strengthens quads without standing. Great for work breaks!", keywords: "leg extensions, seated workout, quad exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Sun Salutation", content: "Do 3 rounds of sun salutations in 5 minutes. Stretches whole body and boosts energy. Follow a YouTube guide for form!", keywords: "sun salutation, morning yoga, full body stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Plank Shoulder Taps", content: "In a plank, tap opposite shoulder with one hand for 20 reps. Builds core stability and shoulder strength. Keep hips steady!", keywords: "plank shoulder taps, core workout, stability exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Hip Bridge", content: "Lie on your back, knees bent, lift hips for 15 reps. Targets glutes and lower back. Squeeze at the top for max effect!", keywords: "hip bridge, glute workout, lower back exercise", image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Chair Yoga for Flexibility", content: "Sit and do 5 seated forward bends, holding each for 10 seconds. Improves flexibility and relaxes back. Perfect for desk workers!", keywords: "chair yoga, flexibility exercise, desk stretches", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Speedy Wall Sit", content: "Hold a wall sit for 30 seconds, rest 10, repeat 3x. Strengthens quads and glutes. Do it while brushing teeth!", keywords: "wall sit, leg strength, quick workout", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Arm Circles for Mobility", content: "Do 20 arm circles forward and backward. Improves shoulder mobility and warms up upper body. No space needed!", keywords: "arm circles, shoulder mobility, quick warm-up", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Lunges While Cooking", content: "Do 10 lunges per leg while waiting for food to cook. Strengthens legs and improves balance. Keep a steady pace!", keywords: "lunges workout, kitchen exercise, leg strength", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Toe Touches", content: "Stand and touch toes for 15 reps, holding 2 seconds each. Stretches hamstrings and back. Great for morning routines!", keywords: "toe touches, hamstring stretch, quick flexibility", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Bicycle Crunches for Abs", content: "Lie down and do 20 bicycle crunches, alternating sides. Targets abs and obliques. Keep it slow for control!", keywords: "bicycle crunches, abs workout, core exercise", image: "https://images.unsplash.com/photo-1518614366606-8a8a9d7e15bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing High Knees", content: "March in place, lifting knees high for 30 seconds. Boosts cardio and warms up legs. Do it during TV ads!", keywords: "high knees, cardio workout, quick exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Neck Release Stretch", content: "Tilt head side-to-side, holding each for 15 seconds. Relieves neck tension from sitting. Do it at your desk!", keywords: "neck stretch, tension relief, desk exercise", image: "https://images.unsplash.com/photo-1509909751488-998f78ad4895?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Calf Stretch on Wall", content: "Push against a wall with one leg back, stretching calf for 20 seconds each side. Improves flexibility and reduces tightness. Easy anywhere!", keywords: "calf stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Push-Up Variation", content: "Do 10 incline push-ups on a counter or table. Easier than floor push-ups, still builds chest strength. Perfect for beginners!", keywords: "incline push-ups, chest workout, beginner exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Core Squeeze", content: "Sit tall, tighten abs for 10 seconds, release, repeat 10x. Strengthens core without moving. Do it during meetings!", keywords: "seated core exercise, abs workout, office fitness", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Jumping Jacks", content: "Do 20 jumping jacks in 30 seconds. Boosts heart rate and works full body. No space or equipment needed!", keywords: "jumping jacks, cardio exercise, quick workout", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Wrist Mobility Drill", content: "Rotate wrists in circles for 20 seconds each direction. Relieves tension from typing. Do it hourly at work!", keywords: "wrist mobility, desk exercise, tension relief", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Single-Leg Balance", content: "Stand on one leg for 20 seconds, switch sides. Improves balance and strengthens ankles. Try it while brushing teeth!", keywords: "single leg balance, ankle strength, quick exercise", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Glute Kicks", content: "Kick one leg back while standing, 15 reps per side. Targets glutes and hamstrings. Do it in the kitchen!", keywords: "glute kicks, hamstring workout, quick exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Arm Stretch", content: "Raise arms overhead, clasp hands, stretch for 15 seconds. Opens chest and boosts energy. Perfect wake-up move!", keywords: "arm stretch, morning exercise, chest opener", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Step-Ups on Stairs", content: "Step up and down on a stair for 20 reps per leg. Builds leg strength and cardio. Use a handrail for safety!", keywords: "step-ups, leg workout, stair exercise", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Angels", content: "Stand against a wall, move arms up and down like snow angels for 15 reps. Improves posture and shoulder mobility. Easy at home!", keywords: "wall angels, posture exercise, shoulder mobility", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Torso Twist", content: "Sit and twist torso side-to-side for 20 reps. Strengthens obliques and improves flexibility. Great for desk breaks!", keywords: "seated torso twist, oblique exercise, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Mountain Climbers", content: "In plank, alternate bringing knees to chest for 30 seconds. Boosts cardio and core strength. No equipment needed!", keywords: "mountain climbers, cardio workout, core exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Ankle Circles for Mobility", content: "Rotate each ankle 10 times in both directions. Improves mobility and prevents stiffness. Do it while sitting!", keywords: "ankle circles, mobility exercise, quick stretch", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Side Lunges", content: "Step to the side, lunge low, alternate for 12 reps. Targets inner thighs and glutes. Keep back straight!", keywords: "side lunges, thigh workout, glute exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Chair Squat Hover", content: "Lower into a squat above a chair, hold for 10 seconds, repeat 5x. Builds leg strength safely. Great for beginners!", keywords: "chair squat, leg workout, beginner exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Arm Pulses", content: "Hold arms out at shoulder height, pulse up and down for 20 seconds. Tones shoulders and arms. No weights needed!", keywords: "arm pulses, shoulder workout, quick exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Knee Lifts", content: "Sit and lift knees toward chest for 15 reps. Engages core and hip flexors. Do it during a call!", keywords: "seated knee lifts, core workout, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Hip Circles", content: "Stand, hands on hips, rotate hips in circles for 20 seconds each direction. Loosens hips and boosts mobility. Fun and easy!", keywords: "hip circles, mobility exercise, quick stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Couch Push-Ups", content: "Do 12 push-ups with hands on a couch edge. Easier on joints, still builds chest strength. Perfect for home!", keywords: "couch push-ups, chest workout, beginner exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Toe Raises", content: "Stand and rise onto toes for 20 reps. Strengthens calves and improves balance. Do it while waiting in line!", keywords: "toe raises, calf workout, quick exercise", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Desk Shoulder Shrugs", content: "Shrug shoulders up and down for 15 reps at your desk. Relieves neck tension and strengthens traps. Quick and discreet!", keywords: "shoulder shrugs, neck relief, desk exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Plank", content: "Hold a plank against a wall for 30 seconds. Easier than floor planks, still builds core. Try it anywhere!", keywords: "wall plank, core workout, beginner exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Hamstring Stretch", content: "Prop one foot on a low surface, lean forward, hold 15 seconds per side. Stretches hamstrings and back. Do it daily!", keywords: "hamstring stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Star Jumps", content: "Jump, spreading arms and legs wide, for 15 reps. Boosts cardio and works full body. Fun and fast!", keywords: "star jumps, cardio workout, full body exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Arm Extensions", content: "Extend arms forward, hold for 10 seconds, repeat 10x. Strengthens shoulders and improves posture. Do it at work!", keywords: "seated arm extensions, shoulder workout, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Glute Squeeze", content: "While standing or sitting, squeeze glutes for 10 seconds, repeat 10x. Tones glutes discreetly. Do it anywhere!", keywords: "glute squeeze, butt workout, quick exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Cat-Cow Stretch", content: "On all fours, alternate arching and rounding back for 10 reps. Improves spine flexibility and energizes you. Takes 2 minutes!", keywords: "cat-cow stretch, spine flexibility, morning exercise", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Squat", content: "Squat against a wall, hold for 20 seconds, repeat 3x. Builds leg endurance without strain. Great for breaks!", keywords: "wall squat, leg endurance, quick workout", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Arm Swings for Warm-Up", content: "Swing arms forward and back for 20 seconds. Warms up shoulders and chest. Do it before any workout!", keywords: "arm swings, warm-up exercise, shoulder mobility", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Side Bends", content: "Stand and bend side-to-side, holding each for 5 seconds, 10 reps. Stretches obliques and improves flexibility. Easy anywhere!", keywords: "side bends, oblique stretch, quick flexibility", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Calf Raises", content: "Sit and raise heels off floor for 20 reps. Strengthens calves without standing. Do it during a movie!", keywords: "seated calf raises, calf workout, quick exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Donkey Kicks", content: "On all fours, kick one leg back, 15 reps per side. Targets glutes and hamstrings. No equipment needed!", keywords: "donkey kicks, glute workout, quick exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Chest Opener", content: "Clasp hands behind back, pull shoulders back, hold 15 seconds. Opens chest and improves posture. Do it daily!", keywords: "chest opener, posture exercise, morning stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Skater Jumps", content: "Jump side-to-side like a speed skater for 20 reps. Boosts cardio and leg strength. Fun and dynamic!", keywords: "skater jumps, cardio workout, leg exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Spine Twist", content: "Sit, twist torso to one side, hold 10 seconds, switch, 10 reps. Improves spine mobility and core strength. Desk-friendly!", keywords: "seated spine twist, core exercise, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Push", content: "Push against a wall with both hands for 20 seconds, repeat 3x. Builds chest and arm strength. Easy for beginners!", keywords: "wall push, chest workout, beginner exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Hip Flexor Stretch", content: "Lunge forward, push hips forward, hold 15 seconds per side. Relieves tight hips from sitting. Do it daily!", keywords: "hip flexor stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Butt Kickers", content: "Jog in place, kicking heels toward glutes for 30 seconds. Boosts cardio and warms up legs. Do it anywhere!", keywords: "butt kickers, cardio workout, quick exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Shoulder Roll", content: "Roll shoulders forward and back for 20 reps. Relieves tension and improves mobility. Perfect for desk breaks!", keywords: "shoulder roll, tension relief, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Lunge", content: "Lunge with one foot against a wall, hold 15 seconds per side. Stretches hip flexors and quads. Easy at home!", keywords: "wall lunge, hip flexor stretch, quick flexibility", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Arm Raises", content: "Raise arms overhead and lower for 15 reps. Tones shoulders and improves mobility. No equipment needed!", keywords: "arm raises, shoulder workout, quick exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Plank Hold", content: "Hold a forearm plank for 20 seconds, repeat 3x. Builds core and full-body strength. Perfect for beginners!", keywords: "plank hold, core workout, beginner exercise", image: "https://images.unsplash.com/photo-1518614366606-8a8a9d7e15bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Hip Stretch", content: "Cross one leg over the other while seated, lean forward, hold 15 seconds per side. Relieves tight hips. Desk-friendly!", keywords: "seated hip stretch, flexibility exercise, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Shadow Boxing", content: "Punch the air for 30 seconds, alternating arms. Boosts cardio and tones arms. Fun and stress-relieving!", keywords: "shadow boxing, cardio workout, arm exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Calf Stretch", content: "Step one foot back, keep it straight, lean forward for 20 seconds per side. Stretches calves and improves flexibility. Do it anywhere!", keywords: "standing calf stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Bridge", content: "Lie with feet on a wall, lift hips for 15 reps. Targets glutes and core. Easy at home!", keywords: "wall bridge, glute workout, core exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Arm Circles", content: "Sit and make small arm circles for 20 seconds each direction. Improves shoulder mobility and tones arms. Desk-friendly!", keywords: "seated arm circles, shoulder mobility, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Step Touch", content: "Step side-to-side, touching opposite foot, for 30 seconds. Boosts cardio and coordination. Do it during ads!", keywords: "step touch, cardio workout, quick exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Spine Stretch", content: "Lie on back, pull knees to chest, hold 20 seconds. Relieves back tension and boosts flexibility. Perfect wake-up move!", keywords: "spine stretch, morning exercise, flexibility workout", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Arm Press", content: "Press palms against a wall at shoulder height for 20 seconds, repeat 3x. Tones arms and chest. Easy anywhere!", keywords: "wall arm press, arm workout, quick exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Leg Stretch", content: "Extend one leg forward while seated, lean toward toes, hold 15 seconds per side. Stretches hamstrings and back. Desk-friendly!", keywords: "seated leg stretch, hamstring stretch, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Reverse Lunges", content: "Step back into a lunge, alternate legs for 12 reps. Builds leg strength and balance. Keep core tight!", keywords: "reverse lunges, leg workout, quick exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Hip Stretch", content: "Cross one leg over the other, sit back slightly, hold 15 seconds per side. Opens hips and improves flexibility. Do it anywhere!", keywords: "standing hip stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Arm Swings", content: "Swing arms side-to-side for 20 seconds. Warms up upper body and boosts mobility. Perfect pre-workout move!", keywords: "arm swings, warm-up exercise, shoulder mobility", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Core Twist", content: "Sit and twist torso side-to-side for 15 reps. Strengthens obliques and improves spine mobility. Great for breaks!", keywords: "seated core twist, oblique workout, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Sit Twist", content: "In a wall sit, twist torso side-to-side for 20 seconds. Combines leg and core work. Challenging but effective!", keywords: "wall sit twist, core workout, leg exercise", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Toe Touch", content: "Bend forward, touch toes, hold 10 seconds, repeat 5x. Stretches hamstrings and lower back. Do it morning or night!", keywords: "standing toe touch, hamstring stretch, quick flexibility", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick High Plank", content: "Hold a high plank on hands for 20 seconds, repeat 3x. Strengthens arms, core, and shoulders. Beginner-friendly!", keywords: "high plank, core workout, beginner exercise", image: "https://images.unsplash.com/photo-1518614366606-8a8a9d7e15bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Neck Stretch", content: "Tilt head toward shoulder, hold 15 seconds per side. Relieves neck tension from screens. Do it hourly!", keywords: "seated neck stretch, tension relief, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Side Plank", content: "Hold a side plank for 15 seconds per side, repeat twice. Targets obliques and improves balance. No equipment needed!", keywords: "side plank, oblique workout, quick exercise", image: "https://images.unsplash.com/photo-1518614366606-8a8a9d7e15bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Arm Stretch", content: "Pull one arm across chest, hold 15 seconds per side. Stretches shoulders and upper back. Great for desk workers!", keywords: "arm stretch, shoulder stretch, quick flexibility", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Knee Push-Ups", content: "Do 10 push-ups on knees. Builds chest and arm strength with less strain. Perfect for beginners!", keywords: "knee push-ups, chest workout, beginner exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Hip Circles", content: "Sit and rotate hips in circles for 20 seconds each direction. Loosens hips and boosts mobility. Desk-friendly!", keywords: "seated hip circles, mobility exercise, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Calf Raise", content: "Lean against a wall, raise heels for 15 reps. Strengthens calves and improves balance. Do it anywhere!", keywords: "wall calf raise, calf workout, quick exercise", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Forward Fold", content: "Stand, bend forward at hips, hold 20 seconds. Stretches hamstrings and back, boosts energy. Perfect wake-up stretch!", keywords: "forward fold, morning stretch, flexibility exercise", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Skips in Place", content: "Skip in place for 30 seconds, lifting knees high. Boosts cardio and coordination. Fun and easy!", keywords: "skips in place, cardio workout, quick exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Chest Opener", content: "Clasp hands behind back while seated, pull shoulders back, hold 15 seconds. Opens chest and improves posture. Desk-friendly!", keywords: "seated chest opener, posture exercise, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Push-Up", content: "Do 15 wall push-ups, keeping elbows close to body. Tones arms and chest without strain. Great for beginners!", keywords: "wall push-up, arm workout, beginner exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Standing Quad Stretch", content: "Pull one foot to glutes, hold 15 seconds per side. Stretches quads and improves flexibility. Use a wall for balance!", keywords: "quad stretch, flexibility exercise, quick stretch", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Arm Pulses Overhead", content: "Raise arms overhead, pulse up and down for 20 seconds. Tones shoulders and boosts circulation. No equipment needed!", keywords: "arm pulses overhead, shoulder workout, quick exercise", image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Side Stretch", content: "Sit and reach one arm overhead, lean to side, hold 10 seconds per side. Stretches obliques and improves flexibility. Desk-friendly!", keywords: "seated side stretch, oblique stretch, office workout", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick Wall Side Lunge", content: "Lunge sideways against a wall, hold 15 seconds per side. Stretches inner thighs and strengthens legs. Easy at home!", keywords: "wall side lunge, thigh stretch, quick exercise", image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Morning Knee Hugs", content: "Lie on back, hug knees to chest, hold 20 seconds. Relieves lower back tension and boosts flexibility. Perfect wake-up move!", keywords: "knee hugs, morning stretch, flexibility exercise", image: "https://images.unsplash.com/photo-1506126279646-b2a0b4f21db6?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Quick High Knee March", content: "March in place, lifting knees high for 20 seconds. Boosts cardio and warms up legs. Do it during breaks!", keywords: "high knee march, cardio workout, quick exercise", image: "https://images.unsplash.com/photo-1538805067-97d03a1e8a14?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" },
    { title: "Seated Wrist Stretch", content: "Extend one arm, pull fingers back with other hand, hold 15 seconds per side. Relieves wrist tension from typing. Desk-friendly!", keywords: "seated wrist stretch, tension relief, office exercise", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80" }
];

let currentIndex = 0;
const contentDiv = document.getElementById('content');

function loadTips(count = 5) {
    for (let i = 0; i < count && currentIndex < tips.length; i++) {
        const tip = tips[currentIndex];
        const tipDiv = document.createElement('article');
        tipDiv.className = 'bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition duration-300';
        tipDiv.innerHTML = `
            <img src="${tip.image}" alt="${tip.title}" class="w-full h-48 object-cover">
            <div class="p-6">
                <h2 class="text-2xl font-bold text-blue-700 uppercase tracking-tight mb-4">${tip.title}</h2>
                <p class="text-gray-600 mb-4">${tip.content}</p>
                <!-- In-content Ad every 3 tips -->
                ${currentIndex % 3 === 2 ? '<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-YOUR_ADSENSE_PUB_ID" data-ad-slot="YOUR_CONTENT_SLOT_ID" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script>' : ''}
                <!-- Sidebar Ad for desktop -->
                <div class="hidden md:block mt-4"><ins class="adsbygoogle" style="display:block; width:300px; height:250px;" data-ad-client="ca-pub-YOUR_ADSENSE_PUB_ID" data-ad-slot="YOUR_SIDEBAR_SLOT_ID"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div>
            </div>
        `;
        contentDiv.appendChild(tipDiv);

        if (i === 0) {
            document.title = `${tip.title} | QuickFit Tips`;
            document.querySelector('meta[name="description"]').setAttribute('content', tip.content.substring(0, 160) + '...');
        }

        currentIndex++;
    }

    if (currentIndex < tips.length) {
        const loadMoreBtn = document.createElement('button');
        loadMoreBtn.className = 'block mx-auto bg-blue-600 text-white px-6 py-3 rounded-full hover:bg-blue-700 transition duration-300';
        loadMoreBtn.textContent = 'Load More Tips';
        loadMoreBtn.onclick = () => { loadMoreBtn.remove(); loadTips(5); };
        contentDiv.appendChild(loadMoreBtn);
    }
}

window.addEventListener('scroll', () => {
    if (window.innerHeight + window.scrollY >= document.body.offsetHeight - 1000 && currentIndex < tips.length) {
        loadTips(3);
    }
});

loadTips();